package fxa

import (
	"errors"
	"fmt"
	"os"
	"testing"
	"time"
)

// Live check against the production FxA auth server; skipped unless
// FFVPN_LIVE_TEST=1 (needs network access).
//
// Documents current production behavior:
//   - /account/credentials/status accepts non-browser clients (errno 102 for
//     unknown accounts).
//   - /account/login is edge-blocked for non-browser clients with a bare
//     HTTP 406 (empty body, generated by the Fastly/Varnish layer) — this is
//     why --profile/--session-token are the recommended auth modes.
func TestLiveAuthServer(t *testing.T) {
	if os.Getenv("FFVPN_LIVE_TEST") != "1" {
		t.Skip("live test disabled; set FFVPN_LIVE_TEST=1")
	}
	c := NewClient("https://api.accounts.firefox.com/v1")
	c.HTTP.Timeout = 20 * time.Second

	email := fmt.Sprintf("ffvpn-nonexistent-%d@example.invalid", time.Now().UnixNano())

	// credentials/status must return a proper FxA protocol error.
	var status credentialsStatus
	err := c.call("POST", "/account/credentials/status", map[string]string{"email": email}, "", &status)
	var apiErr *APIError
	if !errors.As(err, &apiErr) || apiErr.Status != 400 || apiErr.Errno != ErrnoUnknownAccount {
		t.Fatalf("credentials/status: expected errno %d, got %v", ErrnoUnknownAccount, err)
	}

	// login must be edge-blocked with 406 for non-browser clients.
	_, err = c.Login(email, "not-the-real-password-0", "")
	if !errors.As(err, &apiErr) {
		t.Fatalf("login: expected APIError, got %v", err)
	}
	if apiErr.Status != 406 {
		t.Logf("note: login returned status %d (edge behavior may have changed): %v", apiErr.Status, err)
	} else {
		t.Logf("login is edge-blocked for non-browser clients (HTTP 406), as documented")
	}
}
